// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.A.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3566.A.Robot;
import org.usfirst.frc3566.A.RobotMap;

/**
 *
 */
public class DriveWithJoystick extends Command {

	double lPrevious,rPrevious;
	public DriveWithJoystick() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    	requires(Robot.drivetrain);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	lPrevious=rPrevious=0;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	double maxPower=SmartDashboard.getNumber("maxPower", 1);
    	
//    	if(Robot.oi.joystick1.getRawAxis(3)>0)
//    		RobotMap.drive.tankDrive(Robot.oi.joystick1.getRawAxis(3),Robot.oi.joystick1.getRawAxis(3));
//    		else if(Robot.oi.joystick1.getRawAxis(2)>0)
//    			RobotMap.drive.tankDrive(Robot.oi.joystick1.getRawAxis(2)*-1,Robot.oi.joystick1.getRawAxis(2)*-1);
//    			else  RobotMap.drive.tankDrive(Robot.oi.joystick1.getRawAxis(1)*-1*maxPower, 
//    					Robot.oi.joystick1.getRawAxis(5)*-1*maxPower);
    	if(Robot.oi.joystick1.getRawAxis(3)>0)
    		RobotMap.drive.tankDrive(1, 1);
    	else if(Robot.oi.joystick1.getRawAxis(2)>0)
    		RobotMap.drive.tankDrive(0, 0);
    	else  RobotMap.drive.tankDrive(Robot.oi.joystick1.getRawAxis(1)*-1*maxPower, 
				Robot.oi.joystick1.getRawAxis(5)*-1*maxPower);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
