// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.Jan7.commands;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3566.Jan7.Robot;

/**
 *
 */
public class AutonomousCommand extends Command {

    public AutonomousCommand() {
    	
    }

    @Override
    protected void initialize() {
    	Robot.var.gameMessage = DriverStation.getInstance().getGameSpecificMessage();
    	Robot.var.setSwitchScaleSides(); //splits gameMessage into individual message
    	SmartDashboard.putString("OurSwitch", Robot.var.ourSwitchPos+"");
    	SmartDashboard.putString("Scale", Robot.var.ScalePos+"");
    	SmartDashboard.putString("OppSwitch", Robot.var.oppSwitchPos+"");
    }

    @Override
    protected void execute() {
    }

    @Override
    protected boolean isFinished() {
        return false;
    }

    @Override
    protected void end() {
    }

    @Override
    protected void interrupted() {
    }
}
