// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.Jan7.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3566.Jan7.Robot;
import org.usfirst.frc3566.Jan7.RobotMap;

/**
 *
 */
public class DriveWithJoysticks extends Command {
    public DriveWithJoysticks() {
        requires(Robot.driveTrain);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	if(Robot.oi.joystick1.getRawAxis(3)>0)
    		RobotMap.driveTrainDrive.tankDrive(Robot.oi.joystick1.getRawAxis(3),Robot.oi.joystick1.getRawAxis(3));
    	else if(Robot.oi.joystick1.getRawAxis(2)>0)
    		RobotMap.driveTrainDrive.tankDrive(Robot.oi.joystick1.getRawAxis(2)*-1,Robot.oi.joystick1.getRawAxis(2)*-1);
    	else RobotMap.driveTrainDrive.tankDrive(Robot.oi.getJoystick1().getRawAxis(1)*-1, 
    				Robot.oi.getJoystick1().getRawAxis(5)*-1);
    	//if(Robot.oi.joystick1.getRawAxis(3)>0)Robot.driveTrain.goForward(Robot.oi.joystick1.getRawAxis(3));
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
