// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.Jan7;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.sensors.PigeonIMU;

import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX FrontLeft;
    public static WPI_TalonSRX RearLeft;
    public static WPI_TalonSRX FrontRight;
    public static WPI_TalonSRX RearRight;
    public static PigeonIMU pigeon;
    
    public static SpeedControllerGroup left;
    public static SpeedControllerGroup right;
    
    public static DifferentialDrive driveTrainDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        FrontLeft = new WPI_TalonSRX(0);
        
        
        RearLeft = new WPI_TalonSRX(1);
       // RearLeft.setInverted(true);
        
        
        FrontRight = new WPI_TalonSRX(2);
        //FrontRight.setInverted(true);
        pigeon = new PigeonIMU(FrontRight);
       
        //pigeonIMU is connected to the talon with port 2. 
        
        RearRight = new WPI_TalonSRX(3);
        //RearRight.setInverted(true);
        
        
        left = new SpeedControllerGroup(FrontLeft, RearLeft);
        right = new SpeedControllerGroup(FrontRight, RearRight);
        
       driveTrainDrive = new DifferentialDrive(left, right);
        
        
        driveTrainDrive.setSafetyEnabled(true);
        driveTrainDrive.setExpiration(0.1);
        driveTrainDrive.setMaxOutput(1.0);


    }
    
}
