// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team3566.robot.subsystems;

import org.usfirst.frc.team3566.robot.RobotMap;
import org.usfirst.frc.team3566.robot.commands.DriveWithJoysticks;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;



/**
 *
 */
public class DriveTrain extends Subsystem {
	
    private final WPI_TalonSRX FL = RobotMap.FL;
    private final WPI_TalonSRX RL = RobotMap.RL;
    private final WPI_TalonSRX FR = RobotMap.FR;
    private final WPI_TalonSRX RR = RobotMap.RR;
    private final DifferentialDrive drive = RobotMap.drive;


    @Override
    public void initDefaultCommand() {

        setDefaultCommand(new DriveWithJoysticks());
    }

    @Override
    public void periodic() {
    }
    
    public void ramp(double rmp)
    {
    	FL.configOpenloopRamp(rmp,0);
        FR.configOpenloopRamp(rmp,0);
        RL.configOpenloopRamp(rmp,0);
        RR.configOpenloopRamp(rmp,0);
    }
    
    public void runMotor(double spd)
    {
    	FR.set(spd);
    }
    
   public void stopDrive() {
	  FL.stopMotor();
	  RL.stopMotor();
	  FR.stopMotor();
	  RR.stopMotor();
   }

   public void goForward(double spd) {
	   FL.set(spd);
	   RL.set(spd);
	   FR.set(spd);
	   RR.set(spd);
   }
   
   public void rotate(double spd, boolean dir) {
	   FL.set(spd*(dir? 1:-1));
	   FR.set(spd*(dir? -1:1));
	   RL.set(spd*(dir? 1:-1));
	   RR.set(spd*(dir? -1:1));
   }
   
   public void rotate(double spd) {
	   FL.set(spd);
	   FR.set(spd*-1);
	   RL.set(spd);
	   RR.set(spd*-1);
   }

}

