	// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.BoxPickerUpperTest;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX runMotorTalonSRX1;
    public static WPI_TalonSRX runMotorTalonSRX2;
    public static WPI_TalonSRX runMotorTalonSRX4; 
    public static WPI_TalonSRX runMotorTalonSRX5;
    public static DifferentialDrive drive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static final double BMU_GEAR_MOTOR_SPEED =  1.00;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        //runMotorTalonSRX5 = new WPI_TalonSRX(5);
        runMotorTalonSRX2 = new WPI_TalonSRX(2 );
        runMotorTalonSRX1 = new WPI_TalonSRX(1);
        
        runMotorTalonSRX2 = new WPI_TalonSRX(4 );
        runMotorTalonSRX1 = new WPI_TalonSRX(5);
        
        
        //runMotorTalonSRX4.configPeakCurrentLimit(2, 0);
        //runMotorTalonSRX4.configPeakCurrentDuration(0, 0);
        //runMotorTalonSRX4.configContinuousCurrentLimit(1, 0);
        //runMotorTalonSRX4.enableCurrentLimit(true);
        drive = new DifferentialDrive(runMotorTalonSRX1, runMotorTalonSRX2);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
