// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.A;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.sensors.PigeonIMU;

import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX RearLeft;
    public static WPI_TalonSRX RearRight;
    public static WPI_TalonSRX FrontLeft;
    public static WPI_TalonSRX FrontRight;
    
    public static SpeedControllerGroup LeftGroup;
    public static SpeedControllerGroup RightGroup;
    
//    public static PigeonIMU gyro;
    
    public static DifferentialDrive drive;
    //public static PigeonIMU gyro;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        FrontLeft=new WPI_TalonSRX(0);
        //FrontLeft.configOpenloopRamp(0.2, 0);
        RearLeft=new WPI_TalonSRX(1);
        //RearLeft.configOpenloopRamp(0.2, 0);
        FrontRight=new WPI_TalonSRX(2);
        //FrontRight.configOpenloopRamp(0.2, 0);
        RearRight=new WPI_TalonSRX(3);
        //RearRight.configOpenloopRamp(0.2, 0);
        
        LeftGroup=new SpeedControllerGroup(FrontLeft,RearLeft);
        RightGroup=new SpeedControllerGroup(FrontRight,RearRight);
        
//        gyro= new PigeonIMU(FrontRight);
        //to change
        
        drive = new DifferentialDrive(LeftGroup, RightGroup);
        
        drive.setSafetyEnabled(true);
        drive.setExpiration(0.1);
        drive.setMaxOutput(1.0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
