// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.Jan7.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3566.Jan7.Robot;

/**
 *
 */
public class DriveForSeconds extends Command {

	private double spd;
	private boolean dir;
	
    public DriveForSeconds(double timeOut, double speed, boolean direction) {
    	this.setTimeout(timeOut);
    	spd = speed;
    	dir = direction;
    }


    @Override
    protected void initialize() {
    }


    @Override
    protected void execute() {
    	Robot.driveTrain.goForward((dir?1:-1) * spd);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return this.isTimedOut();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.driveTrain.stopDrive();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	end();
    }
}
