// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.Jan7;

import org.usfirst.frc3566.Jan7.commands.*;
import org.usfirst.frc3566.Jan7.subsystems.OpenFieldSimulator;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;



/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
	
    public Joystick joystick1;
    public JoystickButton rotateLeft, rotateRight;
    public JoystickButton openField;


    public OI() {

        joystick1 = new Joystick(0);
        
        rotateLeft = new JoystickButton(joystick1, 5);
        rotateLeft.whileHeld(new RotateNonStop(Robot.var.rotateNonStopSpd*-1));
        
        rotateRight = new JoystickButton(joystick1, 6);
        rotateRight.whileHeld(new RotateNonStop(Robot.var.rotateNonStopSpd));
        
        openField = new JoystickButton(joystick1, 8);
        openField.whenPressed(new OpenFieldSimulator());

        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Rotate", new Rotate());
        SmartDashboard.putData("Perform Route", new CompleteRoute());

    }


    public Joystick getJoystick1() {
        return joystick1;
    }

    public void updateCommands() {
    	
    	SmartDashboard.putData("DriveForSeconds", 
        		new DriveForSomething
        		(false, Robot.var.driveTimeOut, Robot.var.driveSpeed, true));
    	
   //     SmartDashboard.putData("Rotate", new Rotate(Robot.var.rotateAngle, 
     //   		Robot.var.rotateSpeed, Robot.var.rotateDirection));
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

